modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MTI"

[[mods]]
modId = "nanbin"
version = "@version@"
displayName = "Nanbin Create Mod"
updateJSONURL="https://raw.githubusercontent.com/LIEH-SAD/Nanbin-Create-Mod/refs/heads/main/1.20.1/mtr4/update.json"
displayURL = "https://lieh-sad.github.io/nanbin/"
logoFile="icon.png"
authors = "Nanbin-Studio & LIEH-SAD & jh1145"
description = '''
'''

[[dependencies.nanbin]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nanbin]]
modId = "minecraft"
mandatory = true
versionRange = "@minecraftVersion@"
ordering = "NONE"
side = "BOTH"

[[dependencies.nanbin]]
modId = "mtr"
mandatory = false
versionRange = "[4.0.0,4.1.0)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.nanbin]]
modId = "filters"
mandatory = false
versionRange = "[1.0.0,)"
ordering = "BEFORE"
side = "CLIENT"