package com.Nanbin.Items;

import com.Nanbin.Blocks.Blocks;
import com.Nanbin.Init;
import com.Nanbin.ItemsGroup.ItemsGroup;
import com.Nanbin.Registry.RegItem.ItemPhone;
import dev.architectury.registry.registries.DeferredRegister;
import dev.architectury.registry.registries.RegistrySupplier;
import mtr.CreativeModeTabs;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.util.Rarity;
import net.minecraft.util.registry.Registry;

public class Items {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(Init.MOD_ID, Registry.ITEM_KEY);

    public static final RegistrySupplier<Item> PHONE = ITEMS.register("phone", () -> new ItemPhone(new Item.Settings().maxCount(1).group(CreativeModeTabs.CORE.get())));
    public static final RegistrySupplier<Item> CRT_LOGO = ITEMS.register("crt_logo", () -> new BlockItem(Blocks.CRT_LOGO.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_PLATFORM = ITEMS.register("crt_platform", () -> new BlockItem(Blocks.CRT_PLATFORM.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_TICKET_1_ENTER = ITEMS.register("crt_barrier_entrance_1", () -> new BlockItem(Blocks.CRT_TICKET_1_ENTER.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_TICKET_1_EXIT = ITEMS.register("crt_barrier_exit_1", () -> new BlockItem(Blocks.CRT_TICKET_1_EXIT.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_TICKET_2_ENTER = ITEMS.register("crt_barrier_entrance_2", () -> new BlockItem(Blocks.CRT_TICKET_2_ENTER.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_TICKET_2_EXIT = ITEMS.register("crt_barrier_exit_2", () -> new BlockItem(Blocks.CRT_TICKET_2_EXIT.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_TICKET_3_ENTER = ITEMS.register("crt_barrier_entrance_3", () -> new BlockItem(Blocks.CRT_TICKET_3_ENTER.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_TICKET_3_EXIT = ITEMS.register("crt_barrier_exit_3", () -> new BlockItem(Blocks.CRT_TICKET_3_EXIT.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_TICKET_MACHINE_1 = ITEMS.register("crt_ticket_machine_1", () -> new BlockItem(Blocks.CRT_TICKET_MACHINE_1.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_OLD_WALL1 = ITEMS.register("crt_old_wall_1", () -> new BlockItem(Blocks.CRT_OLD_WALL1.get(), new Item.Settings().group(ItemsGroup.CRT).rarity(Rarity.EPIC)));
    public static final RegistrySupplier<Item> CRT_OLD_WALL2 = ITEMS.register("crt_old_wall_2", () -> new BlockItem(Blocks.CRT_OLD_WALL2.get(), new Item.Settings().group(ItemsGroup.CRT).rarity(Rarity.EPIC)));
    public static final RegistrySupplier<Item> CRT_FENCE1 = ITEMS.register("crt_fence_1", () -> new BlockItem(Blocks.CRT_FENCE1.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_FENCE8 = ITEMS.register("crt_fence_8", () -> new BlockItem(Blocks.CRT_FENCE8.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_FENCE9 = ITEMS.register("crt_fence_9", () -> new BlockItem(Blocks.CRT_FENCE9.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_FENCE10 = ITEMS.register("crt_fence_10", () -> new BlockItem(Blocks.CRT_FENCE10.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_FENCE_TICKET = ITEMS.register("crt_fence_ticket", () -> new BlockItem(Blocks.CRT_FENCE_TICKET.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_LIFT_TIPS = ITEMS.register("crt_lift_tips", () -> new BlockItem(Blocks.CRT_LIFT_TIPS.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_LIFT_TIPS_3 = ITEMS.register("crt_lift_tips_3", () -> new BlockItem(Blocks.CRT_LIFT_TIPS_3.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_PSD_CAB_DOOR = ITEMS.register("crt_psd_cab_door", () -> new BlockItem(Blocks.CRT_PSD_CAB_DOOR.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_APG_CAB_DOOR_OLD = ITEMS.register("crt_apg_cab_door_old", () -> new BlockItem(Blocks.CRT_APG_CAB_DOOR_OLD.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_APG_CAB_FENCE_OLD = ITEMS.register("crt_apg_cab_fence_old", () -> new BlockItem(Blocks.CRT_APG_CAB_FENCE_OLD.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_APG_CAB_FENCE_OLD_CONNECT = ITEMS.register("crt_apg_cab_fence_old_connect", () -> new BlockItem(Blocks.CRT_APG_CAB_FENCE_OLD_CONNECT.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_APG_CAB_DOOR_NEW = ITEMS.register("crt_apg_cab_door_new", () -> new BlockItem(Blocks.CRT_APG_CAB_DOOR_NEW.get(), new Item.Settings()));
    public static final RegistrySupplier<Item> BEHAVIORALBLOCK = ITEMS.register("behavioral_block", () -> new BlockItem(Blocks.BEHAVIORALBLOCK.get(), new Item.Settings().group(ItemsGroup.USING_RAILWAY_BUILD)));
    public static final RegistrySupplier<Item> BEHAVIORALBLOCK_ = ITEMS.register("behavioral_block_90", () -> new BlockItem(Blocks.BEHAVIORALBLOCK_.get(), new Item.Settings().group(ItemsGroup.USING_RAILWAY_BUILD)));
    public static final RegistrySupplier<Item> SOUNDPROOFNET_TOP = ITEMS.register("soundproofnet_top", () -> new BlockItem(Blocks.SOUNDPROOFNET_TOP.get(), new Item.Settings().group(ItemsGroup.USING_RAILWAY_BUILD)));
    public static final RegistrySupplier<Item> SOUNDPROOFNET_TOP_2 = ITEMS.register("soundproofnet_top_2", () -> new BlockItem(Blocks.SOUNDPROOFNET_TOP_2.get(), new Item.Settings().group(ItemsGroup.USING_RAILWAY_BUILD)));
    public static final RegistrySupplier<Item> SOUNDPROOFNET_GLASS = ITEMS.register("soundproofnet_glass", () -> new BlockItem(Blocks.SOUNDPROOFNET_GLASS.get(), new Item.Settings().group(ItemsGroup.USING_RAILWAY_BUILD)));
    public static final RegistrySupplier<Item> SOUNDPROOFNET_GLASS_2 = ITEMS.register("soundproofnet_glass_2", () -> new BlockItem(Blocks.SOUNDPROOFNET_GLASS_2.get(), new Item.Settings().group(ItemsGroup.USING_RAILWAY_BUILD)));
    public static final RegistrySupplier<Item> SOUNDPROOFNET_BASE = ITEMS.register("soundproofnet_base", () -> new BlockItem(Blocks.SOUNDPROOFNET_BASE.get(), new Item.Settings().group(ItemsGroup.USING_RAILWAY_BUILD)));
    public static final RegistrySupplier<Item> SOUNDPROOFNET = ITEMS.register("soundproofnet", () -> new BlockItem(Blocks.SOUNDPROOFNET.get(), new Item.Settings().group(ItemsGroup.USING_RAILWAY_BUILD)));
    public static final RegistrySupplier<Item> SOUNDPROOFNET_UP = ITEMS.register("soundproofnet_up", () -> new BlockItem(Blocks.SOUNDPROOFNET_UP.get(), new Item.Settings().group(ItemsGroup.USING_RAILWAY_BUILD)));
    public static final RegistrySupplier<Item> LOGO = ITEMS.register("logo", () -> new BlockItem(Blocks.LOGO.get(), new Item.Settings().group(ItemsGroup.USING_STATION_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> CEILING = ITEMS.register("ceiling", () -> new BlockItem(Blocks.CEILING.get(), new Item.Settings().group(ItemsGroup.USING_STATION_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> CEILING_2 = ITEMS.register("ceiling_2", () -> new BlockItem(Blocks.CEILING_2.get(), new Item.Settings().group(ItemsGroup.USING_STATION_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> CEILING_OVERHEAD = ITEMS.register("ceiling_overhead", () -> new BlockItem(Blocks.CEILING_OVERHEAD.get(), new Item.Settings().group(ItemsGroup.USING_STATION_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> CEILING_OVERHEAD_2 = ITEMS.register("ceiling_overhead_2", () -> new BlockItem(Blocks.CEILING_OVERHEAD_2.get(), new Item.Settings().group(ItemsGroup.USING_STATION_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> STATION_COLOR_CEILING = ITEMS.register("station_color_ceiling", () -> new BlockItem(Blocks.STATION_COLOR_CEILING.get(), new Item.Settings().group(ItemsGroup.USING_STATION_BUILDING_BLOCKS).rarity(Rarity.UNCOMMON)));
    public static final RegistrySupplier<Item> STATION_COLOR_CEILING_2 = ITEMS.register("station_color_ceiling_2", () -> new BlockItem(Blocks.STATION_COLOR_CEILING_2.get(), new Item.Settings().group(ItemsGroup.USING_STATION_BUILDING_BLOCKS).rarity(Rarity.UNCOMMON)));
    public static final RegistrySupplier<Item> CEILING_LIGHT = ITEMS.register("ceiling_light", () -> new BlockItem(Blocks.CEILING_LIGHT.get(), new Item.Settings().group(ItemsGroup.USING_STATION_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> CEILING_LIGHT_2 = ITEMS.register("ceiling_light_2", () -> new BlockItem(Blocks.CEILING_LIGHT_2.get(), new Item.Settings().group(ItemsGroup.USING_STATION_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> ORDINARY_PSD_CAB_DOOR = ITEMS.register("ordinary_psd_cab_door", () -> new BlockItem(Blocks.ORDINARY_PSD_CAB_DOOR.get(), new Item.Settings()));
    public static final RegistrySupplier<Item> PSD_TOP = ITEMS.register("psd_top", () -> new BlockItem(Blocks.PSD_TOP.get(), new Item.Settings().group(ItemsGroup.USING_STATION_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> BLUEFENCE = ITEMS.register("bluefence", () -> new BlockItem(Blocks.BLUEFENCE.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> GREENFENCE = ITEMS.register("greenfence", () -> new BlockItem(Blocks.GREENFENCE.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> METALFENCE = ITEMS.register("metalfence", () -> new BlockItem(Blocks.METALFENCE.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> NANBIN_WHITE_BLOCK = ITEMS.register("white_block", () -> new BlockItem(Blocks.NANBIN_WHITE_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> NANBIN_RED_BLOCK = ITEMS.register("red_block", () -> new BlockItem(Blocks.NANBIN_RED_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> NANBIN_YELLOW_BLOCK = ITEMS.register("yellow_block", () -> new BlockItem(Blocks.NANBIN_YELLOW_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> NANBIN_GREEN_BLOCK = ITEMS.register("green_block", () -> new BlockItem(Blocks.NANBIN_GREEN_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> NANBIN_BLUE_BLOCK = ITEMS.register("blue_block", () -> new BlockItem(Blocks.NANBIN_BLUE_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> NANBIN_PURPLE_BLOCK = ITEMS.register("purple_block", () -> new BlockItem(Blocks.NANBIN_PURPLE_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> NANBIN_PINK_BLOCK = ITEMS.register("pink_block", () -> new BlockItem(Blocks.NANBIN_PINK_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> LIGHT_RED_BLOCK = ITEMS.register("light_red_block", () -> new BlockItem(Blocks.LIGHT_RED_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> LIGHT_YELLOW_BLOCK = ITEMS.register("light_yellow_block", () -> new BlockItem(Blocks.LIGHT_YELLOW_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> LIGHT_GREEN_BLOCK = ITEMS.register("light_green_block", () -> new BlockItem(Blocks.LIGHT_GREEN_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> LIGHT_BLUE_BLOCK = ITEMS.register("light_blue_block", () -> new BlockItem(Blocks.LIGHT_BLUE_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> LIGHT_PURPLE_BLOCK = ITEMS.register("light_purple_block", () -> new BlockItem(Blocks.LIGHT_PURPLE_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> LIGHT_PINK_BLOCK = ITEMS.register("light_pink_block", () -> new BlockItem(Blocks.LIGHT_PINK_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> CRT_RED_WALL_BLOCK = ITEMS.register("crt_red_wall_block", () -> new BlockItem(Blocks.CRT_RED_WALL_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> CRT_YELLOW_WALL_BLOCK = ITEMS.register("crt_yellow_wall_block", () -> new BlockItem(Blocks.CRT_YELLOW_WALL_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> CRT_GREEN_WALL_BLOCK = ITEMS.register("crt_green_wall_block", () -> new BlockItem(Blocks.CRT_GREEN_WALL_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> CRT_BLUE_WALL_BLOCK = ITEMS.register("crt_blue_wall_block", () -> new BlockItem(Blocks.CRT_BLUE_WALL_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> CRT_PURPLE_WALL_BLOCK = ITEMS.register("crt_purple_wall_block", () -> new BlockItem(Blocks.CRT_PURPLE_WALL_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> CRT_PINK_WALL_BLOCK = ITEMS.register("crt_pink_wall_block", () -> new BlockItem(Blocks.CRT_PINK_WALL_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> CRT_GRADIENT_RED_WALL_BLOCK = ITEMS.register("crt_gradient_red_wall_block", () -> new BlockItem(Blocks.CRT_GRADIENT_RED_WALL_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> CRT_GRADIENT_YELLOW_WALL_BLOCK = ITEMS.register("crt_gradient_yellow_wall_block", () -> new BlockItem(Blocks.CRT_GRADIENT_YELLOW_WALL_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> CRT_GRADIENT_GREEN_WALL_BLOCK = ITEMS.register("crt_gradient_green_wall_block", () -> new BlockItem(Blocks.CRT_GRADIENT_GREEN_WALL_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> CRT_GRADIENT_BLUE_WALL_BLOCK = ITEMS.register("crt_gradient_blue_wall_block", () -> new BlockItem(Blocks.CRT_GRADIENT_BLUE_WALL_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> CRT_GRADIENT_PURPLE_WALL_BLOCK = ITEMS.register("crt_gradient_purple_wall_block", () -> new BlockItem(Blocks.CRT_GRADIENT_PURPLE_WALL_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> CRT_GRADIENT_PINK_WALL_BLOCK = ITEMS.register("crt_gradient_pink_wall_block", () -> new BlockItem(Blocks.CRT_GRADIENT_PINK_WALL_BLOCK.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> BLACK_MARBLE = ITEMS.register("black_marble", () -> new BlockItem(Blocks.BLACK_MARBLE.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> WHITE_MARBLE = ITEMS.register("white_marble", () -> new BlockItem(Blocks.WHITE_MARBLE.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> CEMENT = ITEMS.register("cement", () -> new BlockItem(Blocks.CEMENT.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> TERRAZZO = ITEMS.register("terrazzo", () -> new BlockItem(Blocks.TERRAZZO.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> BLACK_TERRAZZO = ITEMS.register("black_terrazzo", () -> new BlockItem(Blocks.BLACK_TERRAZZO.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> PAVEMENT_1 = ITEMS.register("pavement_1", () -> new BlockItem(Blocks.PAVEMENT_1.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> PAVEMENT_1_HALF = ITEMS.register("pavement_1_half", () -> new BlockItem(Blocks.PAVEMENT_1_HALF.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> PAVEMENT_2 = ITEMS.register("pavement_2", () -> new BlockItem(Blocks.PAVEMENT_2.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> PAVEMENT_2_HALF = ITEMS.register("pavement_2_half", () -> new BlockItem(Blocks.PAVEMENT_2_HALF.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> PAVEMENT_3 = ITEMS.register("pavement_3", () -> new BlockItem(Blocks.PAVEMENT_3.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> PAVEMENT_3_HALF = ITEMS.register("pavement_3_half", () -> new BlockItem(Blocks.PAVEMENT_3_HALF.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> PAVEMENT_4 = ITEMS.register("pavement_4", () -> new BlockItem(Blocks.PAVEMENT_4.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> PAVEMENT_4_HALF = ITEMS.register("pavement_4_half", () -> new BlockItem(Blocks.PAVEMENT_4_HALF.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> DRAIN_COVER = ITEMS.register("drain_cover", () -> new BlockItem(Blocks.DRAIN_COVER.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> GRAY_TACTILE_BAVING = ITEMS.register("gray_tactile_paving", () -> new BlockItem(Blocks.GRAY_TACTILE_BAVING.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> GRAY_TACTILE_BAVING_HALF = ITEMS.register("gray_tactile_paving_half", () -> new BlockItem(Blocks.GRAY_TACTILE_BAVING_HALF.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> GRAY_TACTILE_BAVING_CONNECT = ITEMS.register("gray_tactile_paving_connect", () -> new BlockItem(Blocks.GRAY_TACTILE_BAVING_CONNECT.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> GRAY_TACTILE_BAVING_CONNECT_HALF = ITEMS.register("gray_tactile_paving_connect_half", () -> new BlockItem(Blocks.GRAY_TACTILE_BAVING_CONNECT_HALF.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> YELLOW_TACTILE_BAVING = ITEMS.register("yellow_tactile_paving", () -> new BlockItem(Blocks.YELLOW_TACTILE_BAVING.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> YELLOW_TACTILE_BAVING_HALF = ITEMS.register("yellow_tactile_paving_half", () -> new BlockItem(Blocks.YELLOW_TACTILE_BAVING_HALF.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> YELLOW_TACTILE_BAVING_CONNECT = ITEMS.register("yellow_tactile_paving_connect", () -> new BlockItem(Blocks.YELLOW_TACTILE_BAVING_CONNECT.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> YELLOW_TACTILE_BAVING_CONNECT_HALF = ITEMS.register("yellow_tactile_paving_connect_half", () -> new BlockItem(Blocks.YELLOW_TACTILE_BAVING_CONNECT_HALF.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));
    public static final RegistrySupplier<Item> CRT_RIGID_CATENARY_1 = ITEMS.register("crt_rigid_catenary_1", () -> new BlockItem(Blocks.CRT_RIGID_CATENARY_1.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_TEMP_FENCE_1 = ITEMS.register("crt_temp_fence_1", () -> new BlockItem(Blocks.CRT_TEMP_FENCE_1.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> CRT_FENCE_LIFT_TIPS_1 = ITEMS.register("crt_fence_lift_tips_1", () -> new BlockItem(Blocks.CRT_FENCE_LIFT_TIPS_1.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> NRT_TICKET_1_ENTER = ITEMS.register("nrt_barrier_entrance_1", () -> new BlockItem(Blocks.NRT_TICKET_1_ENTER.get(), new Item.Settings().group(ItemsGroup.NRT)));
    public static final RegistrySupplier<Item> NRT_TICKET_1_EXIT = ITEMS.register("nrt_barrier_exit_1", () -> new BlockItem(Blocks.NRT_TICKET_1_EXIT.get(), new Item.Settings().group(ItemsGroup.NRT)));
    public static final RegistrySupplier<Item> CRT_STATION_NAME_1 = ITEMS.register("crt_station_name_1", () -> new BlockItem(Blocks.CRT_STATION_NAME_1.get(), new Item.Settings().group(ItemsGroup.CRT)));
    public static final RegistrySupplier<Item> ROAD_NAME = ITEMS.register("road_name_block", () -> new BlockItem(Blocks.ROAD_NAME.get(), new Item.Settings().group(ItemsGroup.CITY_BUILDING_BLOCKS)));

    public static void init() {
        ITEMS.register();
    }
}
