
package com.Nanbin.Blocks;

import com.Nanbin.ItemsGroup.ItemsGroup;
import com.Nanbin.Registry.RegBlock.*;
import com.Nanbin.Registry.RegBlock.TallFence.*;
import net.minecraft.block.AbstractBlock;
import org.mtr.mapping.holder.Block;
import org.mtr.mapping.holder.Identifier;
import org.mtr.mapping.mapper.BlockExtension;
import org.mtr.mapping.mapper.SlabBlockExtension;
import org.mtr.mapping.registry.BlockRegistryObject;
import org.mtr.mod.block.BlockGlassFence;
import org.mtr.mod.block.BlockPlatform;
import org.mtr.mod.block.BlockStationColor;
import org.mtr.mod.item.ItemBlockEnchanted;

import static com.Nanbin.Registry.Init.MOD_ID;
import  static com.Nanbin.Registry.Init.REGISTRY;
import  static org.mtr.mod.Blocks.createDefaultBlockSettings;

public class Blocks {
    public final static BlockRegistryObject CRT_LOGO;
    public final static BlockRegistryObject CRT_PLATFORM;
    public final static BlockRegistryObject CRT_TICKET_1_ENTER;
    public final static BlockRegistryObject CRT_TICKET_1_EXIT;
    public final static BlockRegistryObject CRT_TICKET_2_ENTER;
    public final static BlockRegistryObject CRT_TICKET_2_EXIT;
    public final static BlockRegistryObject CRT_OLD_WALL1;
    public final static BlockRegistryObject CRT_OLD_WALL2;
    public final static BlockRegistryObject CRT_FENCE1;
    public final static BlockRegistryObject CRT_FENCE8;
    public final static BlockRegistryObject CRT_FENCE9;
    public final static BlockRegistryObject CRT_LIFT_TIPS;
    public final static BlockRegistryObject BEHAVIORALBLOCK;
    public final static BlockRegistryObject BEHAVIORALBLOCK_;
    public final static BlockRegistryObject LOGO;
    public final static BlockRegistryObject CEILING;
    public final static BlockRegistryObject CEILING_LIGHT;
    //public final static BlockRegistryObject PSD_TOP;
    public final static BlockRegistryObject BLUEFENCE;
    public final static BlockRegistryObject BLUEFENCE_TOP;
    public final static BlockRegistryObject GREENFENCE;
    public final static BlockRegistryObject GREENFENCE_TOP;
    public final static BlockRegistryObject METALFENCE;
    public final static BlockRegistryObject METALFENCE_TOP;
    public final static BlockRegistryObject NANBIN_WHITE_BLOCK;
    public final static BlockRegistryObject NANBIN_RED_BLOCK;
    public final static BlockRegistryObject NANBIN_YELLOW_BLOCK;
    public final static BlockRegistryObject NANBIN_GREEN_BLOCK;
    public final static BlockRegistryObject NANBIN_BLUE_BLOCK;
    public final static BlockRegistryObject NANBIN_PURPLE_BLOCK;
    public final static BlockRegistryObject NANBIN_PINK_BLOCK;
    public final static BlockRegistryObject LIGHT_RED_BLOCK;
    public final static BlockRegistryObject LIGHT_YELLOW_BLOCK;
    public final static BlockRegistryObject LIGHT_GREEN_BLOCK;
    public final static BlockRegistryObject LIGHT_BLUE_BLOCK;
    public final static BlockRegistryObject LIGHT_PURPLE_BLOCK;
    public final static BlockRegistryObject LIGHT_PINK_BLOCK;
    public final static BlockRegistryObject CRT_RED_WALL_BLOCK;
    public final static BlockRegistryObject CRT_YELLOW_WALL_BLOCK;
    public final static BlockRegistryObject CRT_GREEN_WALL_BLOCK;
    public final static BlockRegistryObject CRT_BLUE_WALL_BLOCK;
    public final static BlockRegistryObject CRT_PURPLE_WALL_BLOCK;
    public final static BlockRegistryObject CRT_PINK_WALL_BLOCK;
    public final static BlockRegistryObject CRT_GRADIENT_RED_WALL_BLOCK;
    public final static BlockRegistryObject CRT_GRADIENT_YELLOW_WALL_BLOCK;
    public final static BlockRegistryObject CRT_GRADIENT_GREEN_WALL_BLOCK;
    public final static BlockRegistryObject CRT_GRADIENT_BLUE_WALL_BLOCK;
    public final static BlockRegistryObject CRT_GRADIENT_PURPLE_WALL_BLOCK;
    public final static BlockRegistryObject CRT_GRADIENT_PINK_WALL_BLOCK;
    public final static BlockRegistryObject BLACK_MARBLE;
    public final static BlockRegistryObject WHITE_MARBLE;
    public final static BlockRegistryObject CEMENT;
    public final static BlockRegistryObject PAVEMENT_1;
    public final static BlockRegistryObject PAVEMENT_1_HALF;
    public final static BlockRegistryObject PAVEMENT_2;
    public final static BlockRegistryObject PAVEMENT_2_HALF;
    public final static BlockRegistryObject PAVEMENT_3;
    public final static BlockRegistryObject PAVEMENT_3_HALF;
    public final static BlockRegistryObject PAVEMENT_4;
    public final static BlockRegistryObject PAVEMENT_4_HALF;
    public final static BlockRegistryObject DRAIN_COVER;
    public final static BlockRegistryObject GRAY_TACTILE_BAVING;
    public final static BlockRegistryObject GRAY_TACTILE_BAVING_HALF;
    public final static BlockRegistryObject GRAY_TACTILE_BAVING_CONNECT;
    public final static BlockRegistryObject GRAY_TACTILE_BAVING_CONNECT_HALF;
    public final static BlockRegistryObject YELLOW_TACTILE_BAVING;
    public final static BlockRegistryObject YELLOW_TACTILE_BAVING_HALF;
    public final static BlockRegistryObject YELLOW_TACTILE_BAVING_CONNECT;
    public final static BlockRegistryObject YELLOW_TACTILE_BAVING_CONNECT_HALF;

    static {
        CRT_LOGO = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_logo"), () -> new Block(new BlockCRTLogo(AbstractBlock.Settings.create())),ItemsGroup.CRT);
        CRT_PLATFORM = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_platform"), () -> new Block(new BlockPlatform(createDefaultBlockSettings(false), true)), ItemsGroup.CRT);
        CRT_TICKET_1_ENTER = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_barrier_entrance_1"), () -> new Block(new BlockCrtTicket(true)), ItemsGroup.CRT);
        CRT_TICKET_1_EXIT = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_barrier_exit_1"), () -> new Block(new BlockCrtTicket(false)), ItemsGroup.CRT);
        CRT_TICKET_2_ENTER = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_barrier_entrance_2"), () -> new Block(new BlockCrtTicket(true)), ItemsGroup.CRT);
        CRT_TICKET_2_EXIT = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_barrier_exit_2"), () -> new Block(new BlockCrtTicket(false)), ItemsGroup.CRT);
        CRT_OLD_WALL1 = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_old_wall_1"), () -> new Block(new BlockStationColor()), ItemBlockEnchanted::new, ItemsGroup.CRT);
        CRT_OLD_WALL2 = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_old_wall_2"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CRT);
        CRT_LIFT_TIPS = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_lift_tips"), () -> new Block(new BlockMTRLogo(AbstractBlock.Settings.create().nonOpaque())), ItemsGroup.CRT);
        CRT_FENCE1 = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_fence_1"), () -> new Block(new BlockGlassFence()), ItemsGroup.CRT);
        CRT_FENCE8 = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_fence_8"), () -> new Block(new BlockGlassFence()), ItemsGroup.CRT);
        CRT_FENCE9 = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_fence_9"), () -> new Block(new BlockGlassFence()), ItemsGroup.CRT);
        BEHAVIORALBLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "behavioral_block"), () -> new Block(new BlockBehavioral(AbstractBlock.Settings.create())), ItemsGroup.USING_RAILWAY_BUILD);
        BEHAVIORALBLOCK_ = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "behavioral_block_90"), () -> new Block(new BlockBehavioralVertical(AbstractBlock.Settings.create())), ItemsGroup.USING_RAILWAY_BUILD);
        LOGO = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "logo"), () -> new Block(new BlockMTRLogo(AbstractBlock.Settings.create())),ItemsGroup.USING_STATION_BUILDING_BLOCKS);
        CEILING = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "ceiling"), () -> new Block(new BlockCeiling(AbstractBlock.Settings.create())),ItemsGroup.USING_STATION_BUILDING_BLOCKS);
        CEILING_LIGHT = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "ceiling_light"), () -> new Block(new BlockCeilingLight(AbstractBlock.Settings.create())),ItemsGroup.USING_STATION_BUILDING_BLOCKS);
        //PSD_TOP = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "psd_top"), () -> new Block(new BlockPSDTop()), ItemsGroup.USING_STATION_BUILDING_BLOCKS);
        BLUEFENCE = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "bluefence"), () -> new Block(new BlockBlueFence(AbstractBlock.Settings.create().nonOpaque())),ItemsGroup.CITY_BUILDING_BLOCKS);
        BLUEFENCE_TOP = REGISTRY.registerBlock(new Identifier(MOD_ID, "bluefence_top"), () -> new Block(new BlockBlueFenceTop(AbstractBlock.Settings.create().nonOpaque())));
        GREENFENCE = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "greenfence"), () -> new Block(new BlockGreenFence(AbstractBlock.Settings.create().nonOpaque())),ItemsGroup.CITY_BUILDING_BLOCKS);
        GREENFENCE_TOP = REGISTRY.registerBlock(new Identifier(MOD_ID, "greenfence_top"), () -> new Block(new BlockGreenFenceTop(AbstractBlock.Settings.create().nonOpaque())));
        METALFENCE = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "metalfence"), () -> new Block(new BlockMetalFence(AbstractBlock.Settings.create().nonOpaque())),ItemsGroup.CITY_BUILDING_BLOCKS);
        METALFENCE_TOP = REGISTRY.registerBlock(new Identifier(MOD_ID, "metalfence_top"), () -> new Block(new BlockMetalFenceTop(AbstractBlock.Settings.create().nonOpaque())));
        NANBIN_WHITE_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "white_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        NANBIN_RED_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "red_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        NANBIN_YELLOW_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "yellow_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        NANBIN_GREEN_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "green_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        NANBIN_BLUE_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "blue_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        NANBIN_PURPLE_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "purple_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        NANBIN_PINK_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "pink_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        CRT_RED_WALL_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_red_wall_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        CRT_YELLOW_WALL_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_yellow_wall_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        CRT_GREEN_WALL_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_green_wall_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        CRT_BLUE_WALL_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_blue_wall_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        CRT_PURPLE_WALL_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_purple_wall_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        CRT_PINK_WALL_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_pink_wall_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        CRT_GRADIENT_RED_WALL_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_gradient_red_wall_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        CRT_GRADIENT_YELLOW_WALL_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_gradient_yellow_wall_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        CRT_GRADIENT_GREEN_WALL_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_gradient_green_wall_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        CRT_GRADIENT_BLUE_WALL_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_gradient_blue_wall_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        CRT_GRADIENT_PURPLE_WALL_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_gradient_purple_wall_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        CRT_GRADIENT_PINK_WALL_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "crt_gradient_pink_wall_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        LIGHT_RED_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "light_red_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        LIGHT_YELLOW_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "light_yellow_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        LIGHT_GREEN_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "light_green_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        LIGHT_BLUE_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "light_blue_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        LIGHT_PURPLE_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "light_purple_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        LIGHT_PINK_BLOCK = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "light_pink_block"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        BLACK_MARBLE = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "black_marble"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))), ItemsGroup.CITY_BUILDING_BLOCKS);
        WHITE_MARBLE = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "white_marble"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        CEMENT = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "cement"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        PAVEMENT_1 = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "pavement_1"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        PAVEMENT_1_HALF = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "pavement_1_half"), () -> new Block(new SlabBlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        PAVEMENT_2 = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "pavement_2"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        PAVEMENT_2_HALF = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "pavement_2_half"), () -> new Block(new SlabBlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        PAVEMENT_3 = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "pavement_3"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        PAVEMENT_3_HALF = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "pavement_3_half"), () -> new Block(new SlabBlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        PAVEMENT_4 = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "pavement_4"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        PAVEMENT_4_HALF = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "pavement_4_half"), () -> new Block(new SlabBlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        DRAIN_COVER = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "drain_cover"), () -> new Block(new SlabBlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        GRAY_TACTILE_BAVING = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "gray_tactile_paving"), () -> new Block(new BlockFacingBlock(AbstractBlock.Settings.create())) , ItemsGroup.CITY_BUILDING_BLOCKS);
        GRAY_TACTILE_BAVING_HALF = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "gray_tactile_paving_half"), () -> new Block(new BlockFacingSlabBlock(AbstractBlock.Settings.create())) , ItemsGroup.CITY_BUILDING_BLOCKS);
        GRAY_TACTILE_BAVING_CONNECT = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "gray_tactile_paving_connect"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        GRAY_TACTILE_BAVING_CONNECT_HALF = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "gray_tactile_paving_connect_half"), () -> new Block(new SlabBlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        YELLOW_TACTILE_BAVING = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "yellow_tactile_paving"), () -> new Block(new BlockFacingBlock(AbstractBlock.Settings.create())) , ItemsGroup.CITY_BUILDING_BLOCKS);
        YELLOW_TACTILE_BAVING_HALF = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "yellow_tactile_paving_half"), () -> new Block(new BlockFacingSlabBlock(AbstractBlock.Settings.create())) , ItemsGroup.CITY_BUILDING_BLOCKS);
        YELLOW_TACTILE_BAVING_CONNECT = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "yellow_tactile_paving_connect"), () -> new Block(new BlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
        YELLOW_TACTILE_BAVING_CONNECT_HALF = REGISTRY.registerBlockWithBlockItem(new Identifier(MOD_ID, "yellow_tactile_paving_connect_half"), () -> new Block(new SlabBlockExtension(createDefaultBlockSettings(false))) , ItemsGroup.CITY_BUILDING_BLOCKS);
    }

    public static void init() {}
    }
