package com.Nanbin.Blocks;

import com.Nanbin.Init;
import com.Nanbin.Registry.RegBlock.*;
import com.Nanbin.Registry.RegBlock.CabDoor.BlockCRTCabFence;
import com.Nanbin.Registry.RegBlock.CabDoor.BlockCRTCabFenceConnect;
import com.Nanbin.Registry.RegBlock.CabDoor.BlockOrdinaryAPGCabDoor;
import com.Nanbin.Registry.RegBlock.CabDoor.BlockOrdinaryPSDCabDoor;
import com.Nanbin.Registry.RegBlock.SoundproofNet.BlockSoundproofNetBase;
import com.Nanbin.Registry.RegBlock.SoundproofNet.BlockSoundproofNetMiddle;
import com.Nanbin.Registry.RegBlock.SoundproofNet.BlockSoundproofNetTop;
import com.Nanbin.Registry.RegBlock.TallFence.*;
import dev.architectury.registry.registries.DeferredRegister;
import dev.architectury.registry.registries.RegistrySupplier;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.Material;
import net.minecraft.block.SlabBlock;
import net.minecraft.util.registry.Registry;

public class Blocks {
    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(Init.MOD_ID, Registry.BLOCK_KEY);

    public static final RegistrySupplier<Block> CRT_LOGO = BLOCKS.register("crt_logo", () -> new BlockCRTLogo(AbstractBlock.Settings.of(Material.METAL).luminance(state -> 10)));
    public static final RegistrySupplier<Block> CRT_PLATFORM = BLOCKS.register("crt_platform", () -> new BlockCRTPlatform(AbstractBlock.Settings.of(Material.METAL), true));
    public static final RegistrySupplier<Block> CRT_TICKET_1_ENTER = BLOCKS.register("crt_barrier_entrance_1", () -> new BlockCRTTicketBarrier1(true));
    public static final RegistrySupplier<Block> CRT_TICKET_1_EXIT = BLOCKS.register("crt_barrier_exit_1", () -> new BlockCRTTicketBarrier1(false));
    public static final RegistrySupplier<Block> CRT_TICKET_2_ENTER = BLOCKS.register("crt_barrier_entrance_2", () -> new BlockCRTTicketBarrier2(true));
    public static final RegistrySupplier<Block> CRT_TICKET_2_EXIT = BLOCKS.register("crt_barrier_exit_2", () -> new BlockCRTTicketBarrier2(false));
    public static final RegistrySupplier<Block> CRT_TICKET_3_ENTER = BLOCKS.register("crt_barrier_entrance_3", () -> new BlockCRTTicketBarrier3(true));
    public static final RegistrySupplier<Block> CRT_TICKET_3_EXIT = BLOCKS.register("crt_barrier_exit_3", () -> new BlockCRTTicketBarrier3(false));
    public static final RegistrySupplier<Block> CRT_TICKET_MACHINE_1 = BLOCKS.register("crt_ticket_machine_1", () -> new BlockCRTTicketMachine1(AbstractBlock.Settings.of(Material.METAL).luminance(state -> 5)));
    public static final RegistrySupplier<Block> CRT_OLD_WALL1 = BLOCKS.register("crt_old_wall_1", () -> new BlockStationColor(AbstractBlock.Settings.of(Material.GLASS)));
    public static final RegistrySupplier<Block> CRT_OLD_WALL2 = BLOCKS.register("crt_old_wall_2", () -> new BlockStationColor(AbstractBlock.Settings.of(Material.GLASS)));
    public static final RegistrySupplier<Block> CRT_FENCE1 = BLOCKS.register("crt_fence_1", () -> new BlockGlassFence(AbstractBlock.Settings.of(Material.GLASS)));
    public static final RegistrySupplier<Block> CRT_FENCE8 = BLOCKS.register("crt_fence_8", () -> new BlockGlassFence(AbstractBlock.Settings.of(Material.GLASS)));
    public static final RegistrySupplier<Block> CRT_FENCE9 = BLOCKS.register("crt_fence_9", () -> new BlockGlassFence(AbstractBlock.Settings.of(Material.GLASS)));
    public static final RegistrySupplier<Block> CRT_FENCE10 = BLOCKS.register("crt_fence_10", () -> new BlockGlassFenceConnect(AbstractBlock.Settings.of(Material.GLASS)));
    public static final RegistrySupplier<Block> CRT_FENCE_TICKET = BLOCKS.register("crt_fence_ticket", () -> new BlockGlassFence(AbstractBlock.Settings.of(Material.GLASS)));
    public static final RegistrySupplier<Block> CRT_LIFT_TIPS = BLOCKS.register("crt_lift_tips", () -> new BlockPaperShapes(AbstractBlock.Settings.of(Material.GLASS)));
    public static final RegistrySupplier<Block> CRT_LIFT_TIPS_3 = BLOCKS.register("crt_lift_tips_3", () -> new BlockPaperShapes(AbstractBlock.Settings.of(Material.GLASS)));
    public static final RegistrySupplier<Block> CRT_PSD_CAB_DOOR = BLOCKS.register("crt_psd_cab_door", () -> new BlockOrdinaryPSDCabDoor(AbstractBlock.Settings.of(Material.GLASS)));
    public static final RegistrySupplier<Block> CRT_APG_CAB_DOOR_OLD = BLOCKS.register("crt_apg_cab_door_old", () -> new BlockOrdinaryPSDCabDoor(AbstractBlock.Settings.of(Material.GLASS)));
    public static final RegistrySupplier<Block> CRT_APG_CAB_FENCE_OLD = BLOCKS.register("crt_apg_cab_fence_old", () -> new BlockCRTCabFence(AbstractBlock.Settings.of(Material.GLASS)));
    public static final RegistrySupplier<Block> CRT_APG_CAB_FENCE_OLD_CONNECT = BLOCKS.register("crt_apg_cab_fence_old_connect", () -> new BlockCRTCabFenceConnect(AbstractBlock.Settings.of(Material.GLASS)));
    public static final RegistrySupplier<Block> CRT_APG_CAB_DOOR_NEW = BLOCKS.register("crt_apg_cab_door_new", () -> new BlockOrdinaryAPGCabDoor(AbstractBlock.Settings.of(Material.GLASS)));
    public static final RegistrySupplier<Block> BEHAVIORALBLOCK = BLOCKS.register("behavioral_block", () -> new BlockBehavioral(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> BEHAVIORALBLOCK_ = BLOCKS.register("behavioral_block_90", () -> new BlockBehavioralVertical(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> SOUNDPROOFNET_TOP = BLOCKS.register("soundproofnet_top", () -> new BlockSoundproofNetTop(AbstractBlock.Settings.of(Material.METAL)));
    public static final RegistrySupplier<Block> SOUNDPROOFNET_TOP_2 = BLOCKS.register("soundproofnet_top_2", () -> new BlockSoundproofNetTop(AbstractBlock.Settings.of(Material.METAL)));
    public static final RegistrySupplier<Block> SOUNDPROOFNET_GLASS = BLOCKS.register("soundproofnet_glass", () -> new BlockSoundproofNetBase(AbstractBlock.Settings.of(Material.METAL)));
    public static final RegistrySupplier<Block> SOUNDPROOFNET_GLASS_2 = BLOCKS.register("soundproofnet_glass_2", () -> new BlockSoundproofNetBase(AbstractBlock.Settings.of(Material.METAL)));
    public static final RegistrySupplier<Block> SOUNDPROOFNET_BASE = BLOCKS.register("soundproofnet_base", () -> new BlockSoundproofNetBase(AbstractBlock.Settings.of(Material.METAL)));
    public static final RegistrySupplier<Block> SOUNDPROOFNET = BLOCKS.register("soundproofnet", () -> new BlockSoundproofNetBase(AbstractBlock.Settings.of(Material.METAL)));
    public static final RegistrySupplier<Block> SOUNDPROOFNET_UP = BLOCKS.register("soundproofnet_up", () -> new BlockSoundproofNetMiddle(AbstractBlock.Settings.of(Material.METAL)));
    public static final RegistrySupplier<Block> LOGO = BLOCKS.register("logo", () -> new BlockPaperShapes(AbstractBlock.Settings.of(Material.GLASS)));
    public static final RegistrySupplier<Block> CEILING = BLOCKS.register("ceiling", () -> new BlockCeiling(AbstractBlock.Settings.of(Material.METAL)));
    public static final RegistrySupplier<Block> CEILING_2 = BLOCKS.register("ceiling_2", () -> new BlockCeiling(AbstractBlock.Settings.of(Material.METAL)));
    public static final RegistrySupplier<Block> CEILING_OVERHEAD = BLOCKS.register("ceiling_overhead", () -> new BlockCeiling(AbstractBlock.Settings.of(Material.METAL)));
    public static final RegistrySupplier<Block> CEILING_OVERHEAD_2 = BLOCKS.register("ceiling_overhead_2", () -> new BlockCeiling(AbstractBlock.Settings.of(Material.METAL)));
    public static final RegistrySupplier<Block> STATION_COLOR_CEILING = BLOCKS.register("station_color_ceiling", () -> new BlockStationColorCeiling(AbstractBlock.Settings.of(Material.METAL)));
    public static final RegistrySupplier<Block> STATION_COLOR_CEILING_2 = BLOCKS.register("station_color_ceiling_2", () -> new BlockStationColorCeiling(AbstractBlock.Settings.of(Material.METAL)));
    public static final RegistrySupplier<Block> CEILING_LIGHT = BLOCKS.register("ceiling_light", () -> new BlockCeilingLight(AbstractBlock.Settings.of(Material.METAL).luminance(state -> 13)));
    public static final RegistrySupplier<Block> CEILING_LIGHT_2 = BLOCKS.register("ceiling_light_2", () -> new BlockCeilingLight(AbstractBlock.Settings.of(Material.METAL).luminance(state -> 13)));
    public static final RegistrySupplier<Block> ORDINARY_PSD_CAB_DOOR = BLOCKS.register("ordinary_psd_cab_door", () -> new BlockOrdinaryPSDCabDoor(AbstractBlock.Settings.of(Material.GLASS)));
    public static final RegistrySupplier<Block> PSD_TOP = BLOCKS.register("psd_top", () -> new BlockPSDTOP(AbstractBlock.Settings.of(Material.GLASS).luminance(state -> 10)));
    public static final RegistrySupplier<Block> BLUEFENCE = BLOCKS.register("bluefence", () -> new BlockBlueFence(AbstractBlock.Settings.of(Material.METAL).nonOpaque()));
    public static final RegistrySupplier<Block> BLUEFENCE_TOP = BLOCKS.register("bluefence_top", () -> new BlockBlueFenceTop(AbstractBlock.Settings.of(Material.METAL).nonOpaque()));
    public static final RegistrySupplier<Block> GREENFENCE = BLOCKS.register("greenfence", () -> new BlockGreenFence(AbstractBlock.Settings.of(Material.METAL).nonOpaque()));
    public static final RegistrySupplier<Block> GREENFENCE_TOP = BLOCKS.register("greenfence_top", () -> new BlockGreenFenceTop(AbstractBlock.Settings.of(Material.METAL).nonOpaque()));
    public static final RegistrySupplier<Block> METALFENCE = BLOCKS.register("metalfence", () -> new BlockMetalFence(AbstractBlock.Settings.of(Material.METAL).nonOpaque()));
    public static final RegistrySupplier<Block> METALFENCE_TOP = BLOCKS.register("metalfence_top", () -> new BlockMetalFenceTop(AbstractBlock.Settings.of(Material.METAL).nonOpaque()));
    public static final RegistrySupplier<Block> NANBIN_WHITE_BLOCK = BLOCKS.register("white_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> NANBIN_RED_BLOCK = BLOCKS.register("red_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> NANBIN_YELLOW_BLOCK = BLOCKS.register("yellow_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> NANBIN_GREEN_BLOCK = BLOCKS.register("green_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> NANBIN_BLUE_BLOCK = BLOCKS.register("blue_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> NANBIN_PURPLE_BLOCK = BLOCKS.register("purple_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> NANBIN_PINK_BLOCK = BLOCKS.register("pink_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> LIGHT_RED_BLOCK = BLOCKS.register("light_red_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> LIGHT_YELLOW_BLOCK = BLOCKS.register("light_yellow_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> LIGHT_GREEN_BLOCK = BLOCKS.register("light_green_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> LIGHT_BLUE_BLOCK = BLOCKS.register("light_blue_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> LIGHT_PURPLE_BLOCK = BLOCKS.register("light_purple_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> LIGHT_PINK_BLOCK = BLOCKS.register("light_pink_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> CRT_RED_WALL_BLOCK = BLOCKS.register("crt_red_wall_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> CRT_YELLOW_WALL_BLOCK = BLOCKS.register("crt_yellow_wall_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> CRT_GREEN_WALL_BLOCK = BLOCKS.register("crt_green_wall_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> CRT_BLUE_WALL_BLOCK = BLOCKS.register("crt_blue_wall_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> CRT_PURPLE_WALL_BLOCK = BLOCKS.register("crt_purple_wall_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> CRT_PINK_WALL_BLOCK = BLOCKS.register("crt_pink_wall_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> CRT_GRADIENT_RED_WALL_BLOCK = BLOCKS.register("crt_gradient_red_wall_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> CRT_GRADIENT_YELLOW_WALL_BLOCK = BLOCKS.register("crt_gradient_yellow_wall_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> CRT_GRADIENT_GREEN_WALL_BLOCK = BLOCKS.register("crt_gradient_green_wall_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> CRT_GRADIENT_BLUE_WALL_BLOCK = BLOCKS.register("crt_gradient_blue_wall_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> CRT_GRADIENT_PURPLE_WALL_BLOCK = BLOCKS.register("crt_gradient_purple_wall_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> CRT_GRADIENT_PINK_WALL_BLOCK = BLOCKS.register("crt_gradient_pink_wall_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> BLACK_MARBLE = BLOCKS.register("black_marble", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> WHITE_MARBLE = BLOCKS.register("white_marble", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> CEMENT = BLOCKS.register("cement", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> TERRAZZO = BLOCKS.register("terrazzo", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> BLACK_TERRAZZO = BLOCKS.register("black_terrazzo", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> PAVEMENT_1 = BLOCKS.register("pavement_1", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> PAVEMENT_1_HALF = BLOCKS.register("pavement_1_half", () -> new SlabBlock(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> PAVEMENT_2 = BLOCKS.register("pavement_2", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> PAVEMENT_2_HALF = BLOCKS.register("pavement_2_half", () -> new SlabBlock(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> PAVEMENT_3 = BLOCKS.register("pavement_3", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> PAVEMENT_3_HALF = BLOCKS.register("pavement_3_half", () -> new SlabBlock(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> PAVEMENT_4 = BLOCKS.register("pavement_4", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> PAVEMENT_4_HALF = BLOCKS.register("pavement_4_half", () -> new SlabBlock(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> DRAIN_COVER = BLOCKS.register("drain_cover", () -> new SlabBlock(AbstractBlock.Settings.of(Material.METAL)));
    public static final RegistrySupplier<Block> GRAY_TACTILE_BAVING = BLOCKS.register("gray_tactile_paving", () -> new BlockFacingBlock(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> GRAY_TACTILE_BAVING_HALF = BLOCKS.register("gray_tactile_paving_half", () -> new BlockFacingSlabBlock(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> GRAY_TACTILE_BAVING_CONNECT = BLOCKS.register("gray_tactile_paving_connect", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> GRAY_TACTILE_BAVING_CONNECT_HALF = BLOCKS.register("gray_tactile_paving_connect_half", () -> new SlabBlock(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> YELLOW_TACTILE_BAVING = BLOCKS.register("yellow_tactile_paving", () -> new BlockFacingBlock(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> YELLOW_TACTILE_BAVING_HALF = BLOCKS.register("yellow_tactile_paving_half", () -> new BlockFacingSlabBlock(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> YELLOW_TACTILE_BAVING_CONNECT = BLOCKS.register("yellow_tactile_paving_connect", () -> new Block(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> YELLOW_TACTILE_BAVING_CONNECT_HALF = BLOCKS.register("yellow_tactile_paving_connect_half", () -> new SlabBlock(AbstractBlock.Settings.of(Material.STONE)));
    public static final RegistrySupplier<Block> CRT_RIGID_CATENARY_1 = BLOCKS.register("crt_rigid_catenary_1", () -> new BlockCRTRigidCatenary1(AbstractBlock.Settings.of(Material.METAL)));
    public static final RegistrySupplier<Block> CRT_TEMP_FENCE_1 = BLOCKS.register("crt_temp_fence_1", () -> new BlockTempFence(AbstractBlock.Settings.of(Material.METAL)));
    public static final RegistrySupplier<Block> CRT_FENCE_LIFT_TIPS_1 = BLOCKS.register("crt_fence_lift_tips_1", () -> new BlockGlassFence(AbstractBlock.Settings.of(Material.GLASS)));
    public static final RegistrySupplier<Block> NRT_TICKET_1_ENTER = BLOCKS.register("nrt_barrier_entrance_1", () -> new BlockNRTTicketBarrier1(true));
    public static final RegistrySupplier<Block> NRT_TICKET_1_EXIT = BLOCKS.register("nrt_barrier_exit_1", () -> new BlockNRTTicketBarrier1(false));
    public static final RegistrySupplier<Block> CRT_STATION_NAME_1 = BLOCKS.register("crt_station_name_1", () -> new BlockCRTStationName1(AbstractBlock.Settings.of(Material.METAL).nonOpaque()));
    public static final RegistrySupplier<Block> ROAD_NAME = BLOCKS.register("road_name_block", () -> new BlockRoadName(AbstractBlock.Settings.of(Material.METAL).nonOpaque()));

    public static void init() {
        BLOCKS.register();
    }
}