import org.apache.tools.ant.filters.ReplaceTokens
import org.mtr.mod.BuildTools

plugins {
    id "fabric-loom" version "1.10-SNAPSHOT"
}

final BuildTools buildTools = new BuildTools(minecraftVersion, "fabric", mtrVersion, project)

dependencies {
    minecraft "com.mojang:minecraft:${minecraftVersion}"
    mappings "net.fabricmc:yarn:${buildTools.getYarnVersion()}:v2"
    modImplementation "net.fabricmc:fabric-loader:${buildTools.getFabricVersion()}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${buildTools.getFabricApiVersion()}"
    modApi "com.terraformersmc:modmenu:${buildTools.getModMenuVersion()}"
    modApi("ziyue.filters:filters-fabric:${buildTools.getFiltersVersion()}") {
        exclude(group: "net.fabricmc")
    }
    modImplementation "org.mtr:MTR-fabric:${mtrVersion}+${minecraftVersion}"
}

repositories {
    maven { url = "https://maven.terraformersmc.com/" }
}

shadowJar {
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(buildTools.javaLanguageVersion))
    }
    withSourcesJar()
}

tasks.register("setupFiles") {
    copy {
        outputs.upToDateWhen { false }
        from "src/main/fabric.mod.template.json"
        into "src/main/resources"
        filter(ReplaceTokens, tokens: [version: version, minecraftVersion: minecraftVersion])
        rename "(.+).template.json", "\$1.json"
    }
}

compileJava.dependsOn("setupFiles")

build {
    doLast {
        buildTools.copyBuildFile()
    }
}

remapJar {
    dependsOn(shadowJar)
    mustRunAfter(shadowJar)
    inputFile = file(shadowJar.archivePath)
    archiveFileName.set("Nanbin-${version}+${minecraftVersion}+fabric+mtr4.jar")
}